### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [Priyanshu085/PromptHub#1]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by Priyanshu085** [comment]
Thank you for your interest in the project and for suggesting the addition of a license. I'm glad you find it interesting!

I've taken your suggestion to heart and have now working for adding a license to the repository. This license specifies the terms under which the code can be used, providing clear guidelines for contributors and users.

If you have any further questions or suggestions, please don't hesitate to let me know. Your input is greatly appreciated!

Best regards,
@SkyBulk
