### ISSUE TITLE
Optimize menu icons for better visibility and touch responsiveness on mobile devices.

### ISSUE THREAD

**Issue by Priyanshu085** [Priyanshu085/PromptHub#4]
Improve mobile navigation by refining menu icons for clarity and ensuring they are easily tappable.

**Comment by i-meetmori** [comment]
Hello @Priyanshu085 can you please assign this issue to me.

**Comment by Priyanshu085** [comment]
Ok Let's see what you can do

**Comment by Priyanshu085** [comment]
How is the progress?
